[package]
name = "pc-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.38.0" , features = ["full"]}
axum = "0.7.5"
dotenv = "0.15.0"
serde = {version = "1.0.203" , features = ["derive"]}
serde_json = "1.0.117"

[dev-dependencies]
anyhow = "1.0.86"
httpc-test = "0.1.9"
